# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  test-env-vars:
    jobs:
      - build:
          context: Heroku

jobs:
  build:
    docker:
      - image: 'tghastings/code-esaas'
    steps:
      - checkout
      - run:
          name: rspec
          command: bundle install && bundle exec rake db:migrate RAILS_ENV=test && bundle exec rspec
